// Invented sample data. All vendors are fictional.
export const sampleInput = {
  period: '2026-Q1',
  language: 'de',
  expenses: [
    {
      id: 'exp-001',
      date: '2026-01-14',
      description: 'Hotel Übernachtung Kundentermin Beispielstadt, 2 Nächte',
      amount: 238,
      currency: 'EUR',
      vendor: 'Hotel Seeblick Beispielstadt',
      paymentMethod: 'Firmenkreditkarte',
      receiptText: 'Hotel Seeblick\n2 x Übernachtung EZ 222,43\nMwSt 7%: 15,57\nGesamt 238,00 EUR',
    },
    {
      id: 'exp-002',
      date: '2026-01-31',
      description: 'Cloud Hosting und Software-Lizenz Projektverwaltung, Januar',
      amount: 89.25,
      currency: 'EUR',
      vendor: 'Wolkenwerk Hosting (wolkenwerk.example)',
      paymentMethod: 'Lastschrift',
      receiptText: 'Netto 75,00\nUSt. 19 %: 14,25\nBrutto 89,25',
    },
    {
      id: 'exp-003',
      date: '2026-02-05',
      description: 'Diesel Firmenwagen',
      amount: 96.4,
      currency: 'EUR',
      vendor: 'Tankstelle Am Kreisel',
      paymentMethod: 'Tankkarte',
    },
    {
      id: 'exp-004',
      date: '2026-02-11',
      description: 'Bewirtung Geschäftsessen mit Neukunde (3 Personen)',
      amount: 142.8,
      currency: 'EUR',
      vendor: 'Restaurant Zur Alten Mühle',
      paymentMethod: 'Firmenkreditkarte',
      receiptText: 'Speisen und Getränke 120,00\nMwSt 19%: 22,80\nSumme 142,80',
    },
    {
      id: 'exp-005',
      date: '2026-02-20',
      description: 'Jahresabschluss 2025, Honorar Steuerberatung',
      amount: 1785,
      currency: 'EUR',
      vendor: 'Kanzlei Musterfrau & Partner',
      paymentMethod: 'Überweisung',
    },
    {
      id: 'exp-006',
      date: '2026-03-02',
      description: 'Druckerpapier, Toner und Porto',
      amount: 64.9,
      currency: 'EUR',
      vendor: 'Schreibwaren Federkiel',
      paymentMethod: 'Bar',
    },
    {
      id: 'exp-007',
      date: '2026-03-09',
      description: 'Zahlung Nr. 4471',
      amount: 310,
      currency: 'EUR',
      vendor: 'Unbekannt',
      paymentMethod: 'Überweisung',
    },
    {
      id: 'exp-008',
      date: '2026-03-18',
      description: 'Strafzettel Falschparken beim Kundentermin',
      amount: 35,
      currency: 'EUR',
      paymentMethod: 'Überweisung',
    },
  ],
}
