// Invented demo input: open invoices and a missing document at a fictional trade supplier.

export const sampleInput = {
  currentDate: '2026-09-21',
  dryRun: true,
  rules: [
    {
      id: 'rule-1',
      name: 'Freundliche Erinnerung',
      triggerAfterDays: 3,
      escalationLevel: 1,
      channel: 'email',
      maxReminders: 3,
      template:
        'Hallo {{recipient_name}},\n\nvielleicht ist es untergegangen: Zu "{{topic}}" ({{reference}}) fehlt uns noch Ihre Rückmeldung. Offener Betrag: {{amount}}.',
    },
    {
      id: 'rule-2',
      name: 'Deutliche Erinnerung',
      triggerAfterDays: 5,
      escalationLevel: 2,
      channel: 'email',
      maxReminders: 3,
      template:
        'Guten Tag {{recipient_name}},\n\nwir haben Sie bereits an "{{topic}}" ({{reference}}) erinnert und leider noch keine Antwort erhalten. Offener Betrag: {{amount}}. Die Frist ist inzwischen abgelaufen.',
    },
    {
      id: 'rule-3',
      name: 'Letzte Mahnung',
      triggerAfterDays: 5,
      escalationLevel: 3,
      channel: 'email',
      maxReminders: 3,
      template:
        'Sehr geehrte/r {{recipient_name}},\n\ntrotz mehrfacher Erinnerung ist "{{topic}}" ({{reference}}) weiterhin offen. Offener Betrag: {{amount}}.',
    },
  ],
  targets: [
    {
      id: 'target-001',
      recipientEmail: 'buchhaltung@nordlicht-metallbau.example',
      recipientName: 'Frau Petersen',
      subject: 'Rechnung RE-2026-0412',
      context: { topic: 'Rechnung für Wartung Kühlanlage', reference: 'RE-2026-0412', amount: '1.840,00 EUR' },
      createdAt: '2026-09-08',
      remindersSent: 0,
      status: 'active',
    },
    {
      id: 'target-002',
      recipientEmail: 'einkauf@baeckerei-sonnenkorn.example',
      recipientName: 'Herr Albrecht',
      subject: 'Rechnung RE-2026-0377',
      context: { topic: 'Rechnung für Ersatzteile', reference: 'RE-2026-0377', amount: '612,50 EUR' },
      createdAt: '2026-08-28',
      lastContactAt: '2026-09-10',
      remindersSent: 1,
      status: 'active',
    },
    {
      id: 'target-003',
      recipientEmail: 'info@hotel-seeblick.example',
      recipientName: 'Frau Yildiz',
      subject: 'Rechnung RE-2026-0298',
      context: { topic: 'Rechnung für Installation Klimagerät', reference: 'RE-2026-0298', amount: '4.275,00 EUR' },
      createdAt: '2026-07-30',
      lastContactAt: '2026-09-09',
      remindersSent: 3,
      status: 'active',
    },
    {
      id: 'target-004',
      recipientEmail: 'technik@gartencenter-blattwerk.example',
      recipientName: 'Herr Novak',
      subject: 'Unterschriebenes Wartungsprotokoll',
      context: { topic: 'Rücksendung des Wartungsprotokolls', reference: 'WP-2026-118', amount: '–' },
      createdAt: '2026-09-15',
      lastContactAt: '2026-09-18',
      remindersSent: 1,
      status: 'active',
    },
    {
      id: 'target-005',
      recipientEmail: 'office@praxis-lindenhof.example',
      recipientName: 'Frau Dr. Brandt',
      subject: 'Rechnung RE-2026-0401',
      context: { topic: 'Rechnung für Filterwechsel', reference: 'RE-2026-0401', amount: '230,00 EUR' },
      createdAt: '2026-09-01',
      lastContactAt: '2026-09-12',
      remindersSent: 1,
      status: 'completed',
    },
  ],
}
