// Invented sample data (fictional café wholesaler "Bergblick Feinkost", not a real company).
export const sampleInput = {
  checkDate: '2026-03-16',
  expiryWarningDays: 30,
  slowMovingDays: 60,
  items: [
    {
      id: 'SKU-1001',
      name: 'Espressobohnen "Hausmischung" 1 kg',
      currentStock: 12,
      reorderThreshold: 40,
      unit: 'bags',
      avgDailyConsumption: 6,
      lastMovementDate: '2026-03-15',
      unitPrice: 18.5,
      category: 'Kaffee',
    },
    {
      id: 'SKU-1002',
      name: 'Hafermilch Barista 1 l',
      currentStock: 0,
      reorderThreshold: 60,
      unit: 'cartons',
      avgDailyConsumption: 15,
      lastMovementDate: '2026-03-14',
      unitPrice: 1.95,
      category: 'Milchalternativen',
    },
    {
      id: 'SKU-1003',
      name: 'Bio-Vollmilch 1 l',
      currentStock: 85,
      reorderThreshold: 50,
      unit: 'cartons',
      avgDailyConsumption: 20,
      expiryDate: '2026-03-21',
      lastMovementDate: '2026-03-16',
      unitPrice: 1.25,
      category: 'Molkerei',
    },
    {
      id: 'SKU-1004',
      name: 'Schokoladensirup 750 ml',
      currentStock: 30,
      reorderThreshold: 10,
      unit: 'bottles',
      avgDailyConsumption: 0.5,
      expiryDate: '2026-04-08',
      lastMovementDate: '2026-03-10',
      unitPrice: 7.9,
      category: 'Sirup',
    },
    {
      id: 'SKU-1005',
      name: 'Lebkuchengewürz-Sirup (Saisonartikel)',
      currentStock: 24,
      reorderThreshold: 5,
      unit: 'bottles',
      expiryDate: '2026-11-30',
      lastMovementDate: '2025-12-28',
      unitPrice: 8.4,
      category: 'Sirup',
    },
    {
      id: 'SKU-1006',
      name: 'Pappbecher 300 ml',
      currentStock: 4200,
      reorderThreshold: 1000,
      unit: 'pcs',
      avgDailyConsumption: 180,
      lastMovementDate: '2026-03-16',
      unitPrice: 0.06,
      category: 'Verpackung',
    },
  ],
}
